spring.application.name=Cinebot
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/moviesdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=QuocDat
spring.datasource.password=17122005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
tmdb.api.key= "a201884fd42d3f82e7910cc8967ed04f"